// 檔案路徑: src/constants/labAlertConstants.js (全新檔案)

export const ALERT_CAUSES = {
  Albumin: [
    { category: '透析相關', text: '清除率不夠' },
    { category: '飲食相關', text: '吃得種類不對' },
    { category: '飲食相關', text: '食慾差' },
    { category: '飲食相關', text: '進食量不夠' },
    { category: '發炎相關', text: '急性感染與發炎' },
    { category: '發炎相關', text: '慢性發炎' },
    { category: '腸胃道相關', text: '胃出血' },
    { category: '腸胃道相關', text: '慢性腹瀉' },
  ],
  CaXP: [
    { category: '透析相關', text: '清除率不夠' },
    { category: '飲食相關', text: '吃得種類不對' },
    { category: '飲食相關', text: '藥物順應性不好' },
    { category: '飲食相關', text: '藥物劑量不夠' },
    { category: '內分泌相關', text: '副甲狀腺亢進' },
    { category: '內分泌相關', text: '維他命D過量' },
    { category: '腫瘤相關', text: '新發惡性腫瘤' },
  ],
  Hb: [
    { category: '透析相關', text: '清除率不夠' },
    { category: '飲食相關', text: '食慾差' },
    { category: '飲食相關', text: '進食量不夠' },
    { category: '發炎相關', text: '慢性發炎' },
    { category: '腸胃道相關', text: '胃出血' },
    { category: '造血功能相關', text: '缺鐵' },
    { category: '造血功能相關', text: '缺B12/葉酸' },
    { category: '造血功能相關', text: 'ESA不夠' },
  ],
  URR: [
    { category: '透析相關', text: '透析醫囑(AK, BF, DF)' },
    { category: '透析相關', text: '透析時間' },
    { category: '血管通路相關', text: '新建管路' },
    { category: '血管通路相關', text: '靜脈壓高' },
    { category: '血管通路相關', text: '兩針距離近' },
    { category: '血管通路相關', text: '容易Clot' },
    { category: '血管通路相關', text: '再循環率高' },
    { category: '病人相關', text: '透析中容易血壓低' },
    { category: '病人相關', text: '透析中容易抽筋' },
    { category: '病人相關', text: '重多洗不完' },
  ],
}

export const ALERT_SUGGESTIONS = {
  Albumin: [
    { category: '透析相關', text: '調整透析醫囑' },
    { category: '飲食相關', text: '飲食衛教、轉介營養師' },
    { category: '飲食相關', text: '開立促進腸胃蠕動藥物、加強腹部按摩與運動' },
    { category: '飲食相關', text: '增加進食量' },
    { category: '發炎相關', text: '控制感染與發炎' },
    { category: '發炎相關', text: '檢測Ferritin, 加強透析效率' },
    { category: '腸胃道相關', text: '安排胃鏡、開立胃藥' },
    { category: '腸胃道相關', text: '轉介腸胃科、控制腹瀉、飲食調整' },
  ],
  CaXP: [
    { category: '透析相關', text: '調整透析醫囑' },
    { category: '飲食相關', text: '飲食衛教、轉介營養師' },
    { category: '飲食相關', text: '藥物衛教' },
    { category: '飲食相關', text: '調整藥物劑量' },
    { category: '內分泌相關', text: '加強副甲亢藥物使用、安排副甲狀腺超音波、考慮手術' },
    { category: '內分泌相關', text: '暫停Vit D、檢查TB, Sarcoidosis or MM' },
    { category: '腫瘤相關', text: '新發惡性腫瘤' },
  ],
  Hb: [
    { category: '透析相關', text: '調整透析醫囑' },
    { category: '飲食相關', text: '開立促進腸胃蠕動藥物、加強腹部按摩與運動' },
    { category: '飲食相關', text: '增加進食量' },
    { category: '發炎相關', text: '檢測Ferritin, 加強透析效率' },
    { category: '腸胃道相關', text: '安排胃鏡、開立胃藥' },
    { category: '造血功能相關', text: '鐵劑補充、查缺鐵原因' },
    { category: '造血功能相關', text: '補充B群' },
    { category: '造血功能相關', text: '加強ESA、考慮HIF stablizer' },
  ],
  URR: [
    { category: '透析相關', text: '調整透析醫囑' },
    { category: '透析相關', text: '延長透析時間' },
    { category: '血管通路相關', text: '加強熱敷、握球運動衛教' },
    { category: '血管通路相關', text: '考慮轉介CVS評估' },
    { category: '血管通路相關', text: '請上針拉開距離' },
    { category: '血管通路相關', text: 'Heparin加量' },
    { category: '血管通路相關', text: '考慮轉介CVS評估' },
    { category: '病人相關', text: '評估體液狀態、考慮心超、考慮調高DW' },
    { category: '病人相關', text: '矯正低血鈣、缺鐵、考慮調高DW' },
    { category: '病人相關', text: '評估體液狀態、考慮調高DW' },
  ],
}

export const LAB_ITEM_DISPLAY_NAMES = {
  BUN: 'BUN',
  Creatinine: 'Cr',
  Albumin: 'ALB',
  P: 'P',
  Ca: 'Ca',
  Hb: 'Hb',
  Hct: 'Hct',
  Platelet: 'PLT',
  WBC: 'WBC',
  Na: 'Na',
  K: 'K',
  eGFR: 'eGFR',
  GlucoseAC: 'Glucose',
  TotalProtein: 'Total Protein',
  Iron: 'Fe',
  TIBC: 'TIBC',
  Ferritin: 'Ferritin',
  iPTH: 'iPTH',
  PostBUN: 'Post-BUN',
  CaXP: 'Ca x P',
  'Kt/V': 'Kt/V',
  URR: 'URR (%)',
  TSAT: 'TSAT (%)',
  Triglyceride: 'TG',
  LDL: 'LDL',
  ALT: 'ALT',
}
